### ISSUE TITLE
Avoid having to call setup() for methods that return void?

### ISSUE THREAD

**Issue by stealthrabbi** [dvabuzyarov/moq.ts#611]
I have some methods in an interface that my unit under test will be calling. Is it possible to avoid having to call `setup()` on each method? It seems I have to also tell it to return a value when it doesn't

In general, what is the default behavior if a UUT calls a method on a moq that hasn't been setup?

**Comment by dvabuzyarov** [comment]
Interfaces exist only in design time and do not provide any type info at runtime phase. So it is not possible to figure out what methods exist and what don't. The library implements the same behaviour as if you call unexacting method on an object. You can try out something like the following:

```typescript
export class MyMock<T> extends Mock<T> {
  constructor(options) {
    super(options);
    this.setup(It.IsAny())
      .returns(undefined);
  }
}
```

I would't say it is the best way since you can easily miss unexpected interactions.
The best option it is use prototype for objects or define every each method with setup().returns(undefined) pair. 

If you came from c# or java I would say that interfaces are not so valuable as in that languages and could be easily replaced with concrete types.

**Comment by dvabuzyarov** [comment]
> In general, what is the default behavior if a UUT calls a method on a moq that hasn't been setup?

If the library has type informations and can recognise that the method exist then it returns undefined value. Otherwise it behaves like an object without the invoked method.

**Comment by dvabuzyarov** [comment]
May I ask what framework and DI container do you use? I have some experience of auto configuring mock objects with DI, so maybe I can give you some advice.

**Comment by stealthrabbi** [comment]
I would have thought it would have the typed information since I set up the mock for the specific interface I defined.

I am creating a NodeJS library in typescript, and am not using any DI currently. Thanks for your comments.

**Comment by dvabuzyarov** [comment]
Ok, you can try out the [loose configuration](https://github.com/dvabuzyarov/moq.ts/wiki/How-to-implement-a-loose-configuration) or you can specify a target object or use setup().returns(undefined) pattern:

```typescript
    fit("Returns undefined", () => {
        interface ITest {
            func(): void;
        }
        const target = {func: () => undefined};
        const object = new Mock<ITest>({target})
            .object();

        const actual = object.func();
        expect(actual).toBe(undefined);
    });

    fit("Returns undefined", () => {
        interface ITest {
            func(): void;
        }
        const object = new Mock<ITest>()
            .setup(instance => instance.func())
            .returns(undefined)
            .object();

        const actual = object.func();
        expect(actual).toBe(undefined);
    });
```
